swagger: "2.0"
info:
  description: |
    This is a sample set of hashing services.
  version: "1.0.0"
  title: Hashing Service
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: beckmann.benjamin@gmail.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
host: "localhost"
basePath: "/"
tags:
  - name: messages
    description: Two way message hashing service
paths:
  /messages:
    post:
      tags:
        - messages
      summary: Add a new message to the store
      operationId: addMessage
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: body
        name: body
        description: "message to store"
        required: true
        schema:
          $ref: "#/definitions/Message"
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Hash'
        405:
          description: Invalid input
  /messages/{hash}:
    get:
      tags:
        - messages
      summary: Find message by hash
      description: Returns a single message
      operationId: getMsgByHash
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "hash"
        description: Hash of message to return
        required: true
        type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Message'
        400:
          description: Invalid message
        404:
          description: Message not found
definitions:
  Hash:
    type: object
    required:
      - digest
    properties:
      digest:
        type: string
        example: HASH_CODE-24cf462ab47f123deadbeaf8675309deadbeaf8675309
  Message:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        example: foo
