openapi: 3.0.0
info:
  title: Hashing Service
  description: |
    This is a sample set of hashing services.
  termsOfService: http://swagger.io/terms/
  contact:
    email: beckmann.benjamin@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/scrumpi3/messageToHash/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: messages
  description: Two way message hashing service
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /messages:
    post:
      tags:
      - messages
      summary: Add a new pet to the store
      operationId: addPet
      requestBody:
        $ref: '#/components/requestBodies/Hash'
      responses:
        405:
          description: Invalid input
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      x-contentType: application/json
      x-accepts: ""
  /messages/{hash}:
    get:
      tags:
      - messages
      summary: Find message by hash
      description: Returns a single message
      operationId: getMsgByHash
      parameters:
      - name: hash
        in: path
        description: Hash of message to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hash'
            application/xml:
              schema:
                $ref: '#/components/schemas/Hash'
        400:
          description: Invalid message
        404:
          description: Message not found
      security:
      - api_key: []
      x-accepts: application/json
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    Hash:
      required:
      - digest
      type: object
      properties:
        digest:
          type: string
          example: HASH_CODE-24cf462ab47f123deadbeaf8675309deadbeaf8675309
  requestBodies:
    Hash:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Hash'
        application/xml:
          schema:
            $ref: '#/components/schemas/Hash'
      required: true
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
      required: true
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://petstore.swagger.io/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
